version: "3"
services:
  api:
    build: .
    ports:
      - "9090:9090"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
